name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  determine-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci
          GIT_TAG: ${{ steps.gitversion.outputs.tag }}

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint
          run: echo "Version: ${{ steps.gitversion.outputs.version }}"

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
            VERSION: ${{ steps.gitversion.outputs.version }}
        id: test-action
        uses: ./
        with:
            path: "README.md"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.contents }}"

  create-release:
    name: Create release
    needs: [test-typescript, test-action]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
     
        tag: ${{ steps.gitversion.outputs.tag }}
        name: Release ${{ steps.gitversion.outputs.tag }}
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: false
        draft: false
        makeLatest: true
        tag: v2.2.${{ github.run_number }}
        name: Release v2.2.${{ github.run_number }}
        generateReleaseNotes: true
        body: Release 2.2.${{ github.run_number }} of GitHub Actions File Reader V2
