name: "test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - uses: actions/checkout@v4

    - name: Npm install
      run: npm install

    - name: Test
      uses: ./
      id: test
      with:
        path: "package.json"
    
    - name: Test content
      run: echo "${{ steps.test.outputs.contents }}"
